use processmash;
--
-- ER/Studio 7.5 SQL Code Generation
-- Company :      Microsoft
-- Project :      ProcessMash.dm1
-- Author :       Joel
--
-- Date Created : Friday, August 12, 2011 15:59:06
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: APPLICATION 
--

CREATE TABLE APPLICATION(
    APPLICATION_ID         INT            AUTO_INCREMENT,
    APPLICATION_TYPE_ID    INT            NOT NULL,
    NAME                   VARCHAR(80)    NOT NULL,
    NATIVE_APP_ID          VARCHAR(80)    NOT NULL,
    NATIVE_APP_NAME        VARCHAR(80)    NOT NULL,
    NATIVE_APP_SECRET      VARCHAR(80)    NOT NULL,
    ENABLED                INT            DEFAULT 1 NOT NULL,
    CREATED                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED          TIMESTAMP,
    PRIMARY KEY (APPLICATION_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: APPLICATION_CONTEXT 
--

CREATE TABLE APPLICATION_CONTEXT(
    APPLICATION_CONTEXT_ID       INT             AUTO_INCREMENT,
    APPLICATION_ID               INT             NOT NULL,
    CONTEXT_ID                   INT             NOT NULL,
    NAME                         VARCHAR(80),
    NATIVE_PAGE_ID               VARCHAR(80),
    NATIVE_PAGE_NAME             VARCHAR(80),
    NATIVE_PAGE_LINK             VARCHAR(128),
    HEADER_IMAGE                 VARCHAR(80),
    FIRST_TAB_DISPLAY_NAME       VARCHAR(80)     NOT NULL,
    START_ACTION_DISPLAY_NAME    VARCHAR(80)     NOT NULL,
    ENABLED                      INT             DEFAULT 1 NOT NULL,
    CREATED                      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED                TIMESTAMP,
    PRIMARY KEY (APPLICATION_CONTEXT_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: APPLICATION_CONTEXT_PROCESS 
--

CREATE TABLE APPLICATION_CONTEXT_PROCESS(
    APPLICATION_CONTEXT_PROCESS_ID    INT             AUTO_INCREMENT,
    APPLICATION_CONTEXT_ID            INT             NOT NULL,
    PROCESS_ID                        INT             NOT NULL,
    NAME                              VARCHAR(80),
    THUMBNAIL_IMAGE                   VARCHAR(80),
    BF_PROCESS_DESIGN_ID              INT,
    PROCESS_STATUS_HTML               VARCHAR(512),
    ENABLED                           INT             DEFAULT 1 NOT NULL,
    CREATED                           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED                     TIMESTAMP,
    PRIMARY KEY (APPLICATION_CONTEXT_PROCESS_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: APPLICATION_TYPE 
--

CREATE TABLE APPLICATION_TYPE(
    APPLICATION_TYPE_ID    INT            AUTO_INCREMENT,
    NAME                   VARCHAR(80),
    ENABLED                INT            DEFAULT 1 NOT NULL,
    CREATED                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED          TIMESTAMP,
    PRIMARY KEY (APPLICATION_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: CONTEXT 
--

CREATE TABLE CONTEXT(
    CONTEXT_ID       INT            AUTO_INCREMENT,
    BF_CONTEXT_ID    INT,
    NAME             VARCHAR(80),
    DISPLAY_NAME     VARCHAR(80),
    EMAIL            VARCHAR(80),
    ROOT_CODE        VARCHAR(80),
    TIME_ZONE        VARCHAR(3),
    BF_SERVER_URL    VARCHAR(80),
    ENABLED          INT            DEFAULT 1 NOT NULL,
    CREATED          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED    TIMESTAMP,
    PRIMARY KEY (CONTEXT_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: NETWORK 
--

CREATE TABLE NETWORK(
    NETWORK_ID         INT            AUTO_INCREMENT,
    NETWORK_TYPE_ID    INT            NOT NULL,
    NAME               VARCHAR(80),
    OAUTH_ENABLED      INT,
    CREATED            TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED      TIMESTAMP,
    PRIMARY KEY (NETWORK_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: NETWORK_TYPE 
--

CREATE TABLE NETWORK_TYPE(
    NETWORK_TYPE_ID    INT            AUTO_INCREMENT,
    NAME               VARCHAR(80)    NOT NULL,
    CREATED            TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED      TIMESTAMP,
    PRIMARY KEY (NETWORK_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: PROCESS 
--

CREATE TABLE PROCESS(
    PROCESS_ID             INT            AUTO_INCREMENT,
    START_EVENT_TYPE_ID    INT            NOT NULL,
    NAME                   VARCHAR(80),
    THUMBNAIL_IMAGE        VARCHAR(80),
    ENABLED                INT            DEFAULT 1 NOT NULL,
    CREATED                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED          TIMESTAMP,
    PRIMARY KEY (PROCESS_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: START_EVENT_TYPE 
--

CREATE TABLE START_EVENT_TYPE(
    START_EVENT_TYPE_ID    INT            AUTO_INCREMENT,
    NAME                   VARCHAR(80)    NOT NULL,
    CREATED                TIMESTAMP,
    LAST_MODIFIED          TIMESTAMP,
    PRIMARY KEY (START_EVENT_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: USER 
--

CREATE TABLE USER(
    USER_ID                   INT            AUTO_INCREMENT,
    APPLICATION_CONTEXT_ID    INT            NOT NULL,
    BF_USER_ID                INT,
    USER_NAME                 VARCHAR(80),
    DISPLAY_NAME              VARCHAR(80),
    PASSWORD                  VARCHAR(80),
    EMAIL                     VARCHAR(80),
    PROFILE_PIC               VARCHAR(80),
    ENABLED                   INT            DEFAULT 1 NOT NULL,
    CREATED                   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_LOGIN                TIMESTAMP,
    LAST_MODIFIED             TIMESTAMP,
    PRIMARY KEY (USER_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: USER_NETWORK 
--

CREATE TABLE USER_NETWORK(
    USER_NETWORK_ID           INT             AUTO_INCREMENT,
    USER_ID                   INT             NOT NULL,
    APPLICATION_CONTEXT_ID    INT             NOT NULL,
    NETWORK_ID                INT             NOT NULL,
    UID                       VARCHAR(80),
    NETWORK_USER_NAME         VARCHAR(80),
    FIRST_NAME                VARCHAR(80),
    LAST_NAME                 VARCHAR(80),
    LINK                      VARCHAR(80),
    EMAIL                     VARCHAR(80),
    LOCALE                    VARCHAR(10),
    PERMISSIONS               VARCHAR(256),
    ACCESS_TOKEN              VARCHAR(128),
    ACCESS_TOKEN_SECRET       VARCHAR(128),
    ENABLED                   INT             DEFAULT 1 NOT NULL,
    CREATED                   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED             TIMESTAMP,
    PRIMARY KEY (USER_NETWORK_ID)
)ENGINE=INNODB
;



-- 
-- INDEX: XUKAPPLICATION_APP_ID 
--

CREATE UNIQUE INDEX XUKAPPLICATION_APP_ID ON APPLICATION(NATIVE_APP_ID)
;
-- 
-- INDEX: XUKUSER_NETWORK 
--

CREATE UNIQUE INDEX XUKUSER_NETWORK ON USER_NETWORK(UID, APPLICATION_CONTEXT_ID, NETWORK_ID)
;
-- 
-- TABLE: APPLICATION 
--

ALTER TABLE APPLICATION ADD CONSTRAINT XFKAPPLICATION 
    FOREIGN KEY (APPLICATION_TYPE_ID)
    REFERENCES APPLICATION_TYPE(APPLICATION_TYPE_ID)
;


-- 
-- TABLE: APPLICATION_CONTEXT 
--

ALTER TABLE APPLICATION_CONTEXT ADD CONSTRAINT XFKAPPLICATION_CONTEXT1 
    FOREIGN KEY (APPLICATION_ID)
    REFERENCES APPLICATION(APPLICATION_ID)
;

ALTER TABLE APPLICATION_CONTEXT ADD CONSTRAINT XFKAPPLICATION_CONTEXT2 
    FOREIGN KEY (CONTEXT_ID)
    REFERENCES CONTEXT(CONTEXT_ID)
;


-- 
-- TABLE: APPLICATION_CONTEXT_PROCESS 
--

ALTER TABLE APPLICATION_CONTEXT_PROCESS ADD CONSTRAINT XFKAPPLICATION_CONTEXT_PROCESS1 
    FOREIGN KEY (PROCESS_ID)
    REFERENCES PROCESS(PROCESS_ID)
;

ALTER TABLE APPLICATION_CONTEXT_PROCESS ADD CONSTRAINT XFKAPPLICATION_CONTEXT_PROCESS2 
    FOREIGN KEY (APPLICATION_CONTEXT_ID)
    REFERENCES APPLICATION_CONTEXT(APPLICATION_CONTEXT_ID)
;


-- 
-- TABLE: NETWORK 
--

ALTER TABLE NETWORK ADD CONSTRAINT XFKNETWORK_TYPE 
    FOREIGN KEY (NETWORK_TYPE_ID)
    REFERENCES NETWORK_TYPE(NETWORK_TYPE_ID)
;


-- 
-- TABLE: PROCESS 
--

ALTER TABLE PROCESS ADD CONSTRAINT XFKPROCESS 
    FOREIGN KEY (START_EVENT_TYPE_ID)
    REFERENCES START_EVENT_TYPE(START_EVENT_TYPE_ID)
;


-- 
-- TABLE: USER 
--

ALTER TABLE USER ADD CONSTRAINT XFKUSER_APPLICATION_CONTEXT 
    FOREIGN KEY (APPLICATION_CONTEXT_ID)
    REFERENCES APPLICATION_CONTEXT(APPLICATION_CONTEXT_ID)
;


-- 
-- TABLE: USER_NETWORK 
--

ALTER TABLE USER_NETWORK ADD CONSTRAINT XFKUSER_NETWORK1 
    FOREIGN KEY (NETWORK_ID)
    REFERENCES NETWORK(NETWORK_ID)
;

ALTER TABLE USER_NETWORK ADD CONSTRAINT XFKUSER_NETWORK2 
    FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID)
;

ALTER TABLE USER_NETWORK ADD CONSTRAINT XFKUSER_NETWORK_APP_CONTEXT 
    FOREIGN KEY (APPLICATION_CONTEXT_ID)
    REFERENCES APPLICATION_CONTEXT(APPLICATION_CONTEXT_ID)
;


