USE processmash
;
ALTER TABLE USER_NETWORK
    DROP INDEX XUKUSER_NETWORK
;
ALTER TABLE APPLICATION
    DROP INDEX XUKAPPLICATION_APP_ID
;
ALTER TABLE USER_NETWORK
    DROP FOREIGN KEY XFKUSER_NETWORK2
;
ALTER TABLE USER_NETWORK
    DROP FOREIGN KEY XFKUSER_NETWORK1
;
ALTER TABLE USER_NETWORK
    DROP FOREIGN KEY XFKUSER_NETWORK_APP_CONTEXT
;
ALTER TABLE USER
    DROP FOREIGN KEY XFKUSER_APPLICATION_CONTEXT
;
ALTER TABLE NETWORK
    DROP FOREIGN KEY XFKNETWORK_TYPE
;
ALTER TABLE APPLICATION_CONTEXT_PROCESS
    DROP FOREIGN KEY XFKAPPLICATION_CONTEXT_PROCESS1
;
ALTER TABLE APPLICATION_CONTEXT_PROCESS
    DROP FOREIGN KEY XFKAPPLICATION_CONTEXT_PROCESS2
;
ALTER TABLE APPLICATION_CONTEXT
    DROP FOREIGN KEY XFKAPPLICATION_CONTEXT1
;
ALTER TABLE APPLICATION_CONTEXT
    DROP FOREIGN KEY XFKAPPLICATION_CONTEXT2
;
ALTER TABLE APPLICATION
    DROP FOREIGN KEY XFKAPPLICATION
;
ALTER TABLE PROCESS
    DROP FOREIGN KEY XFKPROCESS
;
DROP TABLE USER
;
DROP TABLE USER_NETWORK
;
DROP TABLE PROCESS
;
DROP TABLE NETWORK_TYPE
;
DROP TABLE NETWORK
;
DROP TABLE CONTEXT
;
DROP TABLE APPLICATION_TYPE
;
DROP TABLE APPLICATION_CONTEXT_PROCESS
;
DROP TABLE APPLICATION_CONTEXT
;
DROP TABLE APPLICATION
;
DROP TABLE START_EVENT_TYPE
;

